### ISSUE TITLE
Audio Track Playback Issue

### ISSUE THREAD

**Issue by TA418** [Cog-Creators/Red-Lavalink#130]
The music side of RED was working just fine, then all of a sudden, audio will not play back. I think the upstream Lavalink server needs to be updated.

2022-08-12 01:20:26.950  INFO 146 --- [XNIO-1 I/O-16] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "[REDACTED]"}
2022-08-12 01:32:15.440  INFO 146 --- [XNIO-1 I/O-16] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "[REDACTED]", "track": "QAAAhgIAIUljZSBQb3NlaWRvbiAtIEN4IHNvbmcgKFJldXBsb2FkKQALWW91bmdKaWxrZXIAAAAAAASMEAALVzM5LWdyX1VQN2cAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1XMzktZ3JfVVA3ZwAHeW91dHViZQAAAAAAAAAA", "noReplace": false, "startTime": "0", "pause": false}
2022-08-12 01:32:16.412 ERROR 146 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of W39-gr_UP7g

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
    Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.98-devoxin
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-41-generic
  java.vendor: Debian
  java.version: 11.0.15
  java.runtime.version: 11.0.15+10-post-Debian-1deb11u1
  java.vm.version: 11.0.15+10-post-Debian-1deb11u1
Caused by: java.lang.IllegalStateException: No match found
    at java.base/java.util.regex.Matcher.group(Matcher.java:645) ~[na:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractFromScript(YoutubeSignatureCipherManager.java:243) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getExtractedScript(YoutubeSignatureCipherManager.java:160) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:197) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:46) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:34) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    ... 4 common frames omitted

**Comment by aikaterna** [comment]
Thanks, we are aware and have a Lavalink.jar prepped but there are other PRs to address first.

**Comment by TA418** [comment]
Sounds good. Will wait for a fix to be pushed. Appreciate the swift response.

**Comment by aikaterna** [comment]
I just noticed we're on the Red-Lavalink repo and not the Red-DiscordBot repo so I'm going to move this issue over there as this library is not affected and it's the audio backend side of things that is broken at the moment.
